### ISSUE TITLE
SIGSEGV in g_rw_lock_writer_lock () libderelict_extras-glib.so

### ISSUE THREAD

**Issue by Lord-Evil** [PaulFreund/DerelictGlib#1]
```
#0  0x00007ffff7bbdd98 in g_rw_lock_writer_lock () from /home/evil/Sources/dlang/local/lib/libderelict_extras-glib.so
#1  0x00007ffff44f5075 in ?? () from /usr/lib64/libgobject-2.0.so.0
#2  0x00007ffff7dea1ca in ?? () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7dea2db in ?? () from /lib64/ld-linux-x86-64.so.2
#4  0x00007ffff7dee7b7 in ?? () from /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff7dea074 in ?? () from /lib64/ld-linux-x86-64.so.2
#6  0x00007ffff7dede73 in ?? () from /lib64/ld-linux-x86-64.so.2
#7  0x00007ffff74f9fd9 in ?? () from /lib64/libdl.so.2
#8  0x00007ffff7dea074 in ?? () from /lib64/ld-linux-x86-64.so.2
#9  0x00007ffff74fa589 in ?? () from /lib64/libdl.so.2
#10 0x00007ffff74fa071 in dlopen () from /lib64/libdl.so.2
#11 0x00007ffff7bd54d5 in derelict.util.sharedlib.LoadSharedLib(immutable(char)[]) () from /home/evil/Sources/dlang/local/lib/libderelict-util.so
#12 0x00007ffff7bd5620 in derelict.util.sharedlib.SharedLib.load(immutable(char)[][]) () from /home/evil/Sources/dlang/local/lib/libderelict-util.so
#13 0x00007ffff7bd0a2d in derelict.util.loader.SharedLibLoader.load(immutable(char)[][]) () from /home/evil/Sources/dlang/local/lib/libderelict-util.so
#14 0x00007ffff7bd0991 in derelict.util.loader.SharedLibLoader.load(immutable(char)[]) () from /home/evil/Sources/dlang/local/lib/libderelict-util.so
#15 0x00007ffff7bd0861 in derelict.util.loader.SharedLibLoader.load() () from /home/evil/Sources/dlang/local/lib/libderelict-util.so
#16 0x00000000004040a8 in D main ()
```

```
import derelict.purple.purple;

void main()
{
    DerelictPurple.load();
```

A little help, please?

**Comment by Lord-Evil** [comment]
Works when linked statically...

**Comment by PaulFreund** [comment]
I unfortunately don't remember many details of this implementation, maybe the most recent D implementation version of pipe which uses DerelictPurple and DerelictGlib can help you: https://github.com/PaulFreund/pipe.im/tree/9a9e5ac727c561de01e61ad3368e4a62b4cb1ee0
